import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from 'react';
import {requestNotificationPermission} from "../fcm"
import {  onMessageListener, requestForToken } from '../firebase';
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useEffect(() => {
    // Register service worker
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('/firebase-messaging-sw.js')
        .then((registration) => {
          console.log('Service Worker registered with scope:', registration.scope);
        })
        .catch((error) => {
          console.error('Service Worker registration failed:', error);
        });
    }

    requestForToken();
    let unsubscribe: () => void;
    onMessageListener()
      .then((payload) => {
        // unsubscribe = unsub;
        console.log('Received foreground message:', payload);
        // Optionally show a notification here or handle payload
      })
      .catch((err) => console.error('Failed to receive foreground message', err));
  
    return () => {
      if (unsubscribe) {
        unsubscribe();
      }
    // const unsubscribe = onMessageListener()
    //   .then((payload) => {
    //     console.log('Received foreground message:', payload);
    //     // Optionally show a notification here or handle payload
    //   })
    //   .catch((err) => console.error('Failed to receive foreground message', err));

    // return () => {
    //   if (unsubscribe) {
    //     unsubscribe();
    //   }
    };
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

  
    <div>
      <Toaster/>
     {/* <NotificationComponent/> */}
    </div>

    </>
  );
}
